export const ACTIVE_SUBSCRIPTION_STATUSES = [
  'active',
  'trialing',
  'past_due',
] as const

export const VALID_TIERS = [
  'BASIC',
  'PRO',
  'PROAI',
  'PROPLUS',
  'BUSINESS',
  'BUSINESSPLUS',
  'BUSINESSAI',
  'AIWORKPLACE',
  'AIEMPLOYEES',
  'AIWORKPLACE_CREDITS',
  'AIWORKPLACE_PLUS_CREDITS',
  'AIEMPLOYEES_STARTER_CREDITS',
  'AIEMPLOYEES_LIGHT_CREDITS',
  'AIEMPLOYEES_BASIC_CREDITS',
  'AIEMPLOYEES_STANDARD_CREDITS',
  'AIEMPLOYEES_PLUS_CREDITS',
  'AIEMPLOYEES_BUSINESS_CREDITS',
  'AIBUSINESS_EXPERIMENTAL',
  'ENTERPRISE',
] as const

export const MAX_PROJECT_GUESTS = 20
