export enum ActivityType {
  TASK_CREATED = 'TASK_CREATED',
  TASK_COMMENT_CREATED = 'TASK_COMMENT_CREATED',
  TASK_PROPERTY_UPDATED = 'TASK_PROPERTY_UPDATED',
  PROJECT_CREATED = 'PROJECT_CREATED',
  PROJECT_COMMENT_CREATED = 'PROJECT_COMMENT_CREATED',
  PROJECT_PROPERTY_UPDATED = 'PROJECT_PROPERTY_UPDATED',
  ATTACHMENT_CREATED = 'ATTACHMENT_CREATED',
  ATTACHMENT_DELETED = 'ATTACHMENT_DELETED',
  ATTACHMENT_PROPERTY_UPDATED = 'ATTACHMENT_PROPERTY_UPDATED',
  NOTE_CREATED = 'NOTE_CREATED',
  NOTE_PROPERTY_UPDATED = 'NOTE_PROPERTY_UPDATED',
  CLIENT_SHARE_UPDATED = 'CLIENT_SHARE_UPDATED',
}
